#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;
use File::Basename;
use Sys::CPU;

my $has_parallel;
eval {
    require Parallel::ForkManager;
    $has_parallel = 1;
};
$has_parallel //= 0;

my ($input_bed, $input_bam, $input_depth, $thresholds_str, $output_file);
my $threads;
my $num_args = scalar @ARGV;

GetOptions(
    'bed=s'        => \$input_bed,
    'bam=s'        => \$input_bam,
    'depth=s'      => \$input_depth,
    'thresholds=s' => \$thresholds_str,
    'threads=i'    => \$threads,
    'output=s'     => \$output_file,
) or die "Usage: $0 --bed BED_FILE [--bam BAM_FILE | --depth DEPTH_FILE] [--thresholds THRESHOLDS] [--threads INT] [--output FILE]\n";

if ($num_args == 0) {
    print "Usage: $0 --bed BED_FILE [--bam BAM_FILE | --depth DEPTH_FILE] [--thresholds THRESHOLDS] [--threads INT] [--output FILE]\n";
    exit;
}

die "Bed file is required\n" unless $input_bed;
die "Bed file does not exist: $input_bed\n" unless -e $input_bed;
die "Either bam or depth file is required\n" unless $input_bam || $input_depth;
die "Bam file does not exist: $input_bam\n" if $input_bam && !-e $input_bam;
die "Depth file does not exist: $input_depth\n" if $input_depth && !-e $input_depth;

if (!defined $threads) {
    my $cpu_count = detect_cpu_count();
    $threads = $cpu_count - 2;
    $threads = 1 if $threads < 1;
}

my @thresholds = $thresholds_str ? split /,/, $thresholds_str : (10, 50);

my $sample;
if ($input_bam) {
    my $out_dirname = dirname($input_bam);
    $sample = fileparse($input_bam, qr/\.[^.]*/);
    $input_depth = "$out_dirname/$sample.depth.txt";
    `samtools depth -@ $threads -b $input_bed $input_bam > $input_depth`;
} elsif ($input_depth) {
    $sample = fileparse($input_depth, qr/\.[^.]*/);
}

my %depth_data;
open(my $dfh, '<', $input_depth) or die "Can't open $input_depth: $!";
while (my $line = <$dfh>) {
    chomp $line;
    my ($chr, $pos, $d) = split(/\t/, $line);
    $depth_data{$chr}{$pos} = $d;
}
close $dfh;

my @count_headers = map { $_ . "x" } @thresholds;
my @percentage_headers = map { $_ . "x(%)" } @thresholds;
my @header = ("ID", "chrom", "start", "end", "total_bases", "region", "avg_depth", @count_headers, @percentage_headers);

my @regions;
open(BED, $input_bed) or die "Can't read the bed file: $input_bed";
while (my $rec = <BED>) {
    chomp $rec;
    my ($chr, $start, $end, $info, $temp, $strand) = split(/\t/, $rec);
    my $total_bases = $end - $start;
    $start += 1;
    push @regions, [$chr, $start, $end, $total_bases, $info // "unknown"];
}
close BED;

my %results;
my $pm = Parallel::ForkManager->new($threads);
$pm->run_on_finish(sub {
    my ($pid, $exit_code, $ident, $exit_signal, $core_dump, $data_ref) = @_;
    $results{$ident} = $data_ref;
});

for my $i (0 .. $#regions) {
    my ($chr, $start, $end, $total_bases, $info) = @{ $regions[$i] };
    $pm->start($i) and next;
    my ($avg_depth, @counters, @percentages) = get_depth($chr, $start, $end, $total_bases, \%depth_data, @thresholds);
    $pm->finish(0, ["$sample", $chr, $start, $end, $total_bases, $info, $avg_depth, @counters, @percentages]);
}
$pm->wait_all_children;

if ($output_file) {
    open(OUT, ">$output_file") or die "Can't open $output_file: $!";
    print OUT join("\t", @header) . "\n";
    for my $i (0 .. $#regions) {
        print OUT join("\t", @{ $results{$i} }) . "\n";
    }
    close(OUT);
} else {
    print join("\t", @header) . "\n";
    for my $i (0 .. $#regions) {
        print join("\t", @{ $results{$i} }) . "\n";
    }
}

sub get_depth {
    my ($chr, $start, $end, $total_bases, $depth_ref, @thresholds) = @_;
    my ($sum, $count) = (0, 0);
    my @counters = (0) x scalar @thresholds;
    for my $pos ($start .. $end) {
        next unless exists $depth_ref->{$chr}{$pos};
        my $depth_val = $depth_ref->{$chr}{$pos};
        $sum += $depth_val;
        $count++;
        for my $i (0..$#thresholds) {
            if ($depth_val >= $thresholds[$i]) {
                $counters[$i]++;
            }
        }
    }
    my $avg_depth = $count > 0 ? sprintf("%.2f", $sum / $count) : "0";
    my @percentages = map { sprintf("%.2f", ($_ / $total_bases) * 100) } @counters;
    return ($avg_depth, @counters, @percentages);
}

sub detect_cpu_count {
    my $count = Sys::CPU::cpu_count();
    return ($count && $count =~ /^\d+$/ && $count > 0) ? $count : 4;
}
